language: csharp
solution: jsConnectDotNet.sln

jobs:
  include:
    - dotnet: 2.1.22
      mono: none
      env: DOTNETCORE=netcoreapp2.1
    - dotnet: 3.1.8
      mono: none
      env: DOTNETCORE=netcoreapp3.1
    - mono: latest
      env: DOTNETCORE=netcoreapp3.1

install:
  - nuget restore jsConnectDotNet.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release jsConnectDotNet.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe "./jsConnectDotNet.Tests/bin/Release/$DOTNETCORE/jsConnectDotNet.Tests.dll"