language: csharp
solution: jsConnectDotNet.sln

mono:
  - latest
  - 3.12.0
  - 3.10.0

install:
  - nuget restore jsConnectDotNet.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release jsConnectDotNet.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe "./jsConnectDotNet.Tests/bin/Release/netcoreapp3.1/jsConnectDotNet.Tests.dll"